# A list of perspectives with the format <RIR>.<AWS-Region> TODO link to pages.
perspectives:
  - arin.us-east-2
  - arin.us-west-2
  - ripe.eu-central-1
  - ripe.eu-west-2
  - apnic.ap-northeast-2
  - apnic.ap-southeast-1

# The AWS region name for the API gateway and controller.
api-region: us-east-2

# The default number of perspectives to use.
default-perspective-count: 6

# The default quorum to use.
default-quorum: 5

# Whether to enforce whether two distinct RIR regions must succeed.
enforce-distinct-rir-regions: true

# Path to source code for the functions
source-path: /src/aws_lambda_python

caa-domains:
  - example-ca.example.com
